version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      commands:
        - echo "Installing dependencies"
        - pip install --upgrade pip
        - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Running tests..."
      - pytest -v

  build:
    commands:
      - echo "Build phase complete"

artifacts:
  files:
    - "**/*"
